/oak:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: false
      i_pipeline_type: STEREO
      i_mx_id: 194430104171E31200
      i_nn_type: none
    rgb:
      i_width: 1280
      i_height: 800
